"""add image field to animals

Revision ID: fa4eddf67809
Revises: 9be2c3d503ee
Create Date: 2026-01-20 17:03:09.996679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4eddf67809'
down_revision: Union[str, Sequence[str], None] = '9be2c3d503ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('animals', sa.Column('image_content_type', sa.String(), nullable=True))
    op.drop_column('animals', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('animals', 'image_content_type')
    op.drop_column('animals', 'image_data')
    # ### end Alembic commands ###
